from bababel.exceptions import BababelError


class TaskError(BababelError):
    pass
